# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Workspace\1_Lacewing\4_GUI\0_Debug\Lacewing.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lacewing_dialog(object):
    def setupUi(self, Lacewing_dialog):
        Lacewing_dialog.setObjectName("Lacewing_dialog")
        Lacewing_dialog.resize(721, 724)
        Lacewing_dialog.setAutoFillBackground(False)
        self.centralWidget = QtWidgets.QWidget(Lacewing_dialog)
        self.centralWidget.setObjectName("centralWidget")
        self.system_frame = QtWidgets.QFrame(self.centralWidget)
        self.system_frame.setGeometry(QtCore.QRect(10, 10, 271, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.system_frame.sizePolicy().hasHeightForWidth())
        self.system_frame.setSizePolicy(sizePolicy)
        self.system_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.system_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.system_frame.setObjectName("system_frame")
        self.system_groupBox = QtWidgets.QGroupBox(self.system_frame)
        self.system_groupBox.setGeometry(QtCore.QRect(10, 10, 251, 81))
        self.system_groupBox.setObjectName("system_groupBox")
        self.serial_port_title_label = QtWidgets.QLabel(self.system_groupBox)
        self.serial_port_title_label.setGeometry(QtCore.QRect(10, 20, 80, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_port_title_label.sizePolicy().hasHeightForWidth())
        self.serial_port_title_label.setSizePolicy(sizePolicy)
        self.serial_port_title_label.setObjectName("serial_port_title_label")
        self.serial_port_comboBox = QtWidgets.QComboBox(self.system_groupBox)
        self.serial_port_comboBox.setEnabled(True)
        self.serial_port_comboBox.setGeometry(QtCore.QRect(100, 20, 71, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.serial_port_comboBox.setFont(font)
        self.serial_port_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.serial_port_comboBox.setObjectName("serial_port_comboBox")
        self.serial_port_comboBox.addItem("")
        self.ui_status_title_label = QtWidgets.QLabel(self.system_groupBox)
        self.ui_status_title_label.setGeometry(QtCore.QRect(10, 50, 80, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_status_title_label.sizePolicy().hasHeightForWidth())
        self.ui_status_title_label.setSizePolicy(sizePolicy)
        self.ui_status_title_label.setObjectName("ui_status_title_label")
        self.ui_status_label = QtWidgets.QLabel(self.system_groupBox)
        self.ui_status_label.setGeometry(QtCore.QRect(100, 50, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_status_label.sizePolicy().hasHeightForWidth())
        self.ui_status_label.setSizePolicy(sizePolicy)
        self.ui_status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_status_label.setObjectName("ui_status_label")
        self.console_frame = QtWidgets.QFrame(self.centralWidget)
        self.console_frame.setGeometry(QtCore.QRect(290, 10, 421, 341))
        self.console_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.console_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.console_frame.setObjectName("console_frame")
        self.console_groupBox = QtWidgets.QGroupBox(self.console_frame)
        self.console_groupBox.setGeometry(QtCore.QRect(10, 10, 401, 261))
        self.console_groupBox.setObjectName("console_groupBox")
        self.console_clear_pushButton = QtWidgets.QPushButton(self.console_groupBox)
        self.console_clear_pushButton.setGeometry(QtCore.QRect(320, 230, 69, 22))
        self.console_clear_pushButton.setMinimumSize(QtCore.QSize(69, 22))
        self.console_clear_pushButton.setMaximumSize(QtCore.QSize(69, 22))
        self.console_clear_pushButton.setObjectName("console_clear_pushButton")
        self.console_textEdit = QtWidgets.QTextBrowser(self.console_groupBox)
        self.console_textEdit.setGeometry(QtCore.QRect(10, 20, 381, 201))
        self.console_textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.console_textEdit.setObjectName("console_textEdit")
        self.user_cmd_groupBox = QtWidgets.QGroupBox(self.console_frame)
        self.user_cmd_groupBox.setGeometry(QtCore.QRect(10, 280, 401, 51))
        self.user_cmd_groupBox.setObjectName("user_cmd_groupBox")
        self.user_cmd_lineEdit = QtWidgets.QLineEdit(self.user_cmd_groupBox)
        self.user_cmd_lineEdit.setGeometry(QtCore.QRect(10, 20, 291, 22))
        self.user_cmd_lineEdit.setWhatsThis("")
        self.user_cmd_lineEdit.setPlaceholderText("")
        self.user_cmd_lineEdit.setObjectName("user_cmd_lineEdit")
        self.user_cmd_pushButton = QtWidgets.QPushButton(self.user_cmd_groupBox)
        self.user_cmd_pushButton.setGeometry(QtCore.QRect(320, 20, 69, 22))
        self.user_cmd_pushButton.setMinimumSize(QtCore.QSize(69, 22))
        self.user_cmd_pushButton.setMaximumSize(QtCore.QSize(69, 22))
        self.user_cmd_pushButton.setObjectName("user_cmd_pushButton")
        Lacewing_dialog.setCentralWidget(self.centralWidget)

        self.retranslateUi(Lacewing_dialog)
        self.user_cmd_lineEdit.returnPressed.connect(self.user_cmd_pushButton.click)
        QtCore.QMetaObject.connectSlotsByName(Lacewing_dialog)

    def retranslateUi(self, Lacewing_dialog):
        _translate = QtCore.QCoreApplication.translate
        Lacewing_dialog.setWindowTitle(_translate("Lacewing_dialog", "Lacewing @ Imperial College London"))
        self.system_groupBox.setTitle(_translate("Lacewing_dialog", "System Settings"))
        self.serial_port_title_label.setText(_translate("Lacewing_dialog", "Serial Port:"))
        self.serial_port_comboBox.setItemText(0, _translate("Lacewing_dialog", "Refresh"))
        self.ui_status_title_label.setText(_translate("Lacewing_dialog", "Status:"))
        self.ui_status_label.setText(_translate("Lacewing_dialog", "IDLE"))
        self.console_groupBox.setTitle(_translate("Lacewing_dialog", "Console"))
        self.console_clear_pushButton.setText(_translate("Lacewing_dialog", "clear"))
        self.user_cmd_groupBox.setTitle(_translate("Lacewing_dialog", "Debug Interface for Designer"))
        self.user_cmd_lineEdit.setText(_translate("Lacewing_dialog", "Input your command here"))
        self.user_cmd_pushButton.setText(_translate("Lacewing_dialog", "send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Lacewing_dialog = QtWidgets.QMainWindow()
    ui = Ui_Lacewing_dialog()
    ui.setupUi(Lacewing_dialog)
    Lacewing_dialog.show()
    sys.exit(app.exec_())
